 version: 2
 workflows:
   version: 2
   test:
     jobs:
       - test-auth
       - test-categories
 jobs:
   test-auth:
     docker:
       - image: circleci/python:3.8.0
     steps:
       - checkout
       - run: python ynab.test-auth.AuthTest
   test-categories:
     docker:
       - image: circleci/python:3.8.0
     steps:
       - checkout
       - run: python -m ynab.test-categories.CategoryListTests
       - run: python -m ynab.test-categories.CategoryStorageTests
